[features]
seeds = false
skip-lint = false
[programs.devnet]
stone_programs = "B4JQj82q7VaHfXb6JHTXwM46feQ7mSeSEki7JCcEeEGj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/dannydang/.config/solana/id.json"

[scripts]
test = "node tests/stone-program.js"
