[features]
seeds = false
skip-lint = false
[programs.localnet]
stone_programs = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dannydang/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
